apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::262046511657:role/ng-general-eks-node-group-20260322040120086500000003
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::262046511657:user/ks-dev-user
      username: ks-dev-user
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-22T04:11:23Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1008"
  uid: efeb8c5e-7c05-4022-b163-dfca4be6c428
