name: Terraform Plan (prod)

on:
  pull_request:
    paths:
      - 'infra/env/prod/**'
      - 'infra/modules/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # required for OIDC
      contents: read
      pull-requests: write

    defaults:
      run:
        working-directory: infra/env/prod

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::262046511657:oidc-provider/token.actions.githubusercontent.com
        aws-region: ap-south-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -no-color -out=tfplan

    - name: Upload Plan File
      uses: actions/upload-artifact@v4
      with:
        name: tfplan
        path: infra/env/prod/tfplan
