name: Build and Push Docker Images to ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - "infra/premium-frontend/**"
      - "infra/premium-backend/**"
      - "infra/premium-frontend/Dockerfile"
      - "infra/premium-backend/Dockerfile"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production   # because your secrets are stored in this environment

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262046511657:role/ksd-cicd-role
          aws-region: ap-south-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ================================
      # ✅ FRONTEND IMAGE
      # ================================
      - name: Build & Push Frontend Image
        run: |
          FRONT_IMAGE="${{ secrets.FRONT_ECR_URI }}:latest"
          echo "Building frontend image: $FRONT_IMAGE"
          docker build -t $FRONT_IMAGE ./infra/premium-frontend
          docker push $FRONT_IMAGE

      # ================================
      # ✅ BACKEND IMAGE
      # ================================
      - name: Build & Push Backend Image
        run: |
          BACK_IMAGE="${{ secrets.BACKEND_ECR_URI }}:latest"
          echo "Building backend image: $BACK_IMAGE"
          docker build -t $BACK_IMAGE ./infra/premium-backend
          docker push $BACK_IMAGE
